lib/tree_chat_web/router.ex
defmodule TreeChatWeb.Router do
  use TreeChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_user_token
    plug :put_user_name
    plug :put_user_first
    plug :put_user_last
    plug :put_user_id
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TreeChatWeb do
    pipe_through :browser

    get "/", RedirectController, :index
    get "/c/:chat_topic", PageController, :index
    get "/sitemap", PageController, :sitemap
    post "/search", SearchController, :index
    resources "/chat", ChatController, only: [:create, :index, :new, :show]
    resources "/message", MessageController, only: [:show]
    resources "/user", UserController, only: [:create, :new, :edit, :update]
    resources "/password", PasswordController, only: [:new, :create]
    get "/privacy-policy", PrivacyPolicyController, :index
    get "/terms-of-service", TermsOfServiceController, :index
    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
    get "/auth/google/callback", GoogleAuthController, :index
  end

  scope "/api", TreeChatWeb do
    pipe_through :api

    resources "/messages", API.MessageController, only: [:index]
  end

  defp put_user_token(conn, _) do
    if current_user_id = Plug.Conn.get_session(conn, :current_user_id) do
      token = Phoenix.Token.sign(conn, "user socket", current_user_id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  defp put_user_name(conn, _) do
    if current_user_name = Plug.Conn.get_session(conn, :current_user_name) do
      assign(conn, :user_name, current_user_name)
    else
      conn
    end
  end

  defp put_user_first(conn, _) do
    if current_user_first = Plug.Conn.get_session(conn, :current_user_first) do
      assign(conn, :user_first, current_user_first)
    else
      conn
    end
  end

  defp put_user_last(conn, _) do
    if current_user_last = Plug.Conn.get_session(conn, :current_user_last) do
      assign(conn, :user_last, current_user_last)
    else
      conn
    end
  end

  defp put_user_id(conn, _) do
    if current_user_id = Plug.Conn.get_session(conn, :current_user_id) do
      assign(conn, :user_id, Integer.to_string(current_user_id))
    else
      conn
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TreeChatWeb do
  #   pipe_through :api
  # end
end

lib/tree_chat_web/templates/page/edit_password.html.eex
<h3>Change Password</h3>
<%= form_for @conn, user_path(@conn, :update, String.to_integer(@conn.assigns[:user_id])), [as: :user], fn f -> %>
  <%= text_input f, :username, placeholder: "username" %><br>
  <%= password_input f, :password, placeholder: "password" %><br>
  <%= password_input f, :new_password, placeholder: "new_password" %><br>
  <%= submit "Submit" %>
<% end %>

lib/tree_chat_web/templates/page/index.html.eex
<h1 class="chat-title"><%= "#{@current_chat.topic}" %></h1>
  <span id="new-chat-link">Create a Chat</span>
  <%= if @current_chat do %>
    <%= raw "<span class='chat-description' id='#{@current_chat.id}'>#{@current_chat.description}</span>"%>
  <% end %>

  <section class="chat-container">
    <div class="chat-list">
      <%= for chat <- @chats do %>
        <div class="chat">
          <span class="chat-topic"><%= link("#{chat.topic}", to: "/c/#{chat.topic}") %></span>
        </div>
      <% end %>
    </div>

    <div class="reply-window" id="reply-window">
    </div>

    <div class="chat-window" id="chat-window">
      <%= for {message, i} <- Enum.with_index(@messages) do %>
        <%= if i == 0 do %>
          <%= raw "<span id='pagination-trigger' data-cursor-after='#{@metadata.after}' data-chat-id='#{@current_chat.id}'></span>" %>
        <% end %>

        <%= raw "<div class='message' id='message-id-#{message.id}'>"%>
          <span class="message-name"><%= decorate_name(message.name) %></span>
          <% # https://img.youtube.com/vi/youtubevideoid/sddefault.jpg %>
          <%= raw "<span class='message-inserted-at' id='message-share-id-#{message.id}' data-message-id='#{message.id}' data-chat-id='#{message.chat_id}' data-message-name='#{message.name}' data-message-body='#{message.body}'>"%>
            <%= "#{elem(Timex.format(message.inserted_at, "{relative}", :relative), 1)}"%>
            <i class="far fa-share-square"></i>
          </span>
          <br>
          <%= raw decorate_message(message.body)%>
        </div>


        <% {reply_count_acc, reply_span_acc} = reply_count_and_spans(@replies, message)  %>
        <%= raw "<span id='message-replies-container-#{message.id}'>" %>
          <%= raw reply_span_acc %>
        <%= raw "</span>" %>

        <%= if reply_count_acc > 0 do %>
          <%= raw "<span class='add-new-reply-button' id='reply-message-id-#{message.id}' data-message-id='#{message.id}'>#{reply_count_acc} Replies</span>" %>
        <%= else %>
          <%= raw "<span class='add-new-reply-button' id='reply-message-id-#{message.id}' data-message-id='#{message.id}'>+Reply</span>" %>
        <% end %>

        <%= raw "<span class='add-new-reaction-button reaction-button' id='reaction-message-id-#{message.id}'>+🙂</span>" %>
        <%= for reaction <- @reactions do %>
          <%= if message.id == reaction.id do %>
            <%= case Enum.any?(reaction.message.reactions, & "#{&1.user_id}" == @conn.assigns[:user_id] && &1.value == reaction.reaction) do %>
              <%= true -> %>
                <%= raw "<span class='reaction-button decrement-reaction-button' id='message-id-#{message.id}-#{reaction.reaction}' data-count=#{reaction.count} data-reaction=#{reaction.reaction} data-message-id=#{message.id}>#{reaction.count}#{reaction.reaction}</span>" %>
              <%= false -> %>
                <%= raw "<span class='reaction-button increment-reaction-button' id='message-id-#{message.id}-#{reaction.reaction}' data-count=#{reaction.count} data-reaction=#{reaction.reaction} data-message-id=#{message.id}>#{reaction.count}#{reaction.reaction}</span>" %>
            <% end %>
          <% end %>
        <% end %>

        <%= if i == length(@messages) - 1 do %>
          <%= raw "<span id='before-pagination-trigger' data-cursor-before='#{@metadata.before}' data-chat-id='#{@current_chat.id}'></span>" %>
        <% end %>
      <% end %>
    </div>
  </section>

  <form id="chat-form" name="chat-form">
    <textarea type="text" placeholder="Enter to send; Shift+Enter for new line" class="message-input" id="user-msg" form="chat-form"></textarea>
  </form>

  <div id="new-chat-modal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span>
      <%= render "new_chat.html", Map.put(assigns, :action, Routes.chat_path(@conn, :create)) %>
    </div>
  </div>

lib/tree_chat_web/templates/page/new_chat.html.eex
<h3 class="form-header">/c/ChatTopic</h3>

<%= form_for :chat, chat_path(@conn, :create), [as: :chat], fn f -> %>
  <div class="form-element">
    <%= text_input f, :topic, placeholder: "ChatTopic", required: true, class: "form-input" %>
    <%= error_tag f, :topic %>
  </div>
  <div class="form-element">
    <%= textarea f, :description, placeholder: "Description of chat topic.", required: true, class: "form-input" %>
    <%= error_tag f, :description%>
  </div>
  <div>
    <%= hidden_input f, :created_by, [value: @conn.assigns[:user_id]] %>
    <%= error_tag f, :user_id %>
  </div>
  <div class="form-element">
    <%= submit "Submit", class: "form-submit" %>
  </div>
<% end %>

lib/tree_chat_web/templates/page/sitemap.xml.eex
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://cooler.chat</loc>
    <lastmod>2022-11-18</lastmod>
    <changefreq>monthly</changefreq>
  </url>
  <% alias TreeChat.Chat %>
  <%= for chat <- @chats do %>
    <url>
      <loc><%= "https://cooler.chat/c/#{chat.topic}"%></loc>
      <changefreq>daily</changefreq>
    </url>
  <% end %>
</urlset>

lib/tree_chat_web/templates/page/user_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <div>
    <%= label f, :username %>
    <%= text_input f, :username %>
    <%= error_tag f, :username %>
  </div>
  <div>
    <%= label f, :full_name %>
    <%= text_input f, :full_name %>
    <%= error_tag f, :full_name %>
  </div>
  <div>
    <%= label f, :email %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>
  </div>
  <div>
    <%= label f, :password %>
    <%= password_input f, :encrypted_password %>
    <%= error_tag f, :encrypted_password %>
  </div>
  <div>
    <%= submit "Submit" %>
  </div>
<% end %>