lib/tree_chat_web/router.ex
defmodule TreeChatWeb.Router do
  use TreeChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_user_token
    plug :put_user_name
    plug :put_user_first
    plug :put_user_last
    plug :put_user_id
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TreeChatWeb do
    pipe_through :browser

    get "/", RedirectController, :index
    get "/c/:chat_topic", PageController, :index
    get "/sitemap", PageController, :sitemap
    post "/search", SearchController, :index
    resources "/chat", ChatController, only: [:create, :index, :new, :show]
    resources "/message", MessageController, only: [:show]
    resources "/user", UserController, only: [:create, :new, :edit, :update]
    resources "/password", PasswordController, only: [:new, :create]
    get "/privacy-policy", PrivacyPolicyController, :index
    get "/terms-of-service", TermsOfServiceController, :index
    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
    get "/auth/google/callback", GoogleAuthController, :index
  end

  scope "/api", TreeChatWeb do
    pipe_through :api

    resources "/messages", API.MessageController, only: [:index]
  end

  defp put_user_token(conn, _) do
    if current_user_id = Plug.Conn.get_session(conn, :current_user_id) do
      token = Phoenix.Token.sign(conn, "user socket", current_user_id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  defp put_user_name(conn, _) do
    if current_user_name = Plug.Conn.get_session(conn, :current_user_name) do
      assign(conn, :user_name, current_user_name)
    else
      conn
    end
  end

  defp put_user_first(conn, _) do
    if current_user_first = Plug.Conn.get_session(conn, :current_user_first) do
      assign(conn, :user_first, current_user_first)
    else
      conn
    end
  end

  defp put_user_last(conn, _) do
    if current_user_last = Plug.Conn.get_session(conn, :current_user_last) do
      assign(conn, :user_last, current_user_last)
    else
      conn
    end
  end

  defp put_user_id(conn, _) do
    if current_user_id = Plug.Conn.get_session(conn, :current_user_id) do
      assign(conn, :user_id, Integer.to_string(current_user_id))
    else
      conn
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TreeChatWeb do
  #   pipe_through :api
  # end
end

lib/tree_chat_web/views/layout_view.ex
defmodule TreeChatWeb.LayoutView do
  use TreeChatWeb, :view
  alias TreeChat.Accounts
end

lib/tree_chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= if @current_chat do %>
      <title><%= "#{@current_chat.topic}" %></title>
    <% else %>
      <title><%= "Search" %></title>
    <% end %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-E9X63WJPR7"></script>
    <script src="https://kit.fontawesome.com/83dd8e5900.js" crossorigin="anonymous"></script>
    <%= if Application.get_env(:tree_chat, :env) == :prod do %>
      <script>
        (function(c,a){if(!a.__SV){var b=window;try{var d,m,j,k=b.location,f=k.hash;d=function(a,b){return(m=a.match(RegExp(b+"=([^&]*)")))?m[1]:null};f&&d(f,"state")&&(j=JSON.parse(decodeURIComponent(d(f,"state"))),"mpeditor"===j.action&&(b.sessionStorage.setItem("_mpcehash",f),history.replaceState(j.desiredHash||"",c.title,k.pathname+k.search)))}catch(n){}var l,h;window.mixpanel=a;a._i=[];a.init=function(b,d,g){function c(b,i){var a=i.split(".");2==a.length&&(b=b[a[0]],i=a[1]);b[i]=function(){b.push([i].concat(Array.prototype.slice.call(arguments,
        0)))}}var e=a;"undefined"!==typeof g?e=a[g]=[]:g="mixpanel";e.people=e.people||[];e.toString=function(b){var a="mixpanel";"mixpanel"!==g&&(a+="."+g);b||(a+=" (stub)");return a};e.people.toString=function(){return e.toString(1)+".people (stub)"};l="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking start_batch_senders people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
        for(h=0;h<l.length;h++)c(e,l[h]);var f="set set_once union unset remove delete".split(" ");e.get_group=function(){function a(c){b[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));e.push([d,call2])}}for(var b={},d=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<f.length;c++)a(f[c]);return b};a._i.push([b,d,g])};a.__SV=1.2;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
        MIXPANEL_CUSTOM_LIB_URL:"file:"===c.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}})(document,window.mixpanel||[]);
        mixpanel.init("386630652b595b71edfd4b77d7b18df3", {batch_requests: true})

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-E9X63WJPR7');

        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-XXXXX-Y', 'auto');
        ga('send', 'pageview');
      </script>
    <% else %>
      <script>
        (function(c,a){if(!a.__SV){var b=window;try{var d,m,j,k=b.location,f=k.hash;d=function(a,b){return(m=a.match(RegExp(b+"=([^&]*)")))?m[1]:null};f&&d(f,"state")&&(j=JSON.parse(decodeURIComponent(d(f,"state"))),"mpeditor"===j.action&&(b.sessionStorage.setItem("_mpcehash",f),history.replaceState(j.desiredHash||"",c.title,k.pathname+k.search)))}catch(n){}var l,h;window.mixpanel=a;a._i=[];a.init=function(b,d,g){function c(b,i){var a=i.split(".");2==a.length&&(b=b[a[0]],i=a[1]);b[i]=function(){b.push([i].concat(Array.prototype.slice.call(arguments,
        0)))}}var e=a;"undefined"!==typeof g?e=a[g]=[]:g="mixpanel";e.people=e.people||[];e.toString=function(b){var a="mixpanel";"mixpanel"!==g&&(a+="."+g);b||(a+=" (stub)");return a};e.people.toString=function(){return e.toString(1)+".people (stub)"};l="disable time_event track track_pageview track_links track_forms track_with_groups add_group set_group remove_group register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking start_batch_senders people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user people.remove".split(" ");
        for(h=0;h<l.length;h++)c(e,l[h]);var f="set set_once union unset remove delete".split(" ");e.get_group=function(){function a(c){b[c]=function(){call2_args=arguments;call2=[c].concat(Array.prototype.slice.call(call2_args,0));e.push([d,call2])}}for(var b={},d=["get_group"].concat(Array.prototype.slice.call(arguments,0)),c=0;c<f.length;c++)a(f[c]);return b};a._i.push([b,d,g])};a.__SV=1.2;b=c.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?
        MIXPANEL_CUSTOM_LIB_URL:"file:"===c.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";d=c.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)}})(document,window.mixpanel||[]);
        mixpanel.init("TEST", {batch_requests: true})

        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-TEST');

        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-XXXXX-Y', 'auto');
        ga('send', 'pageview');
      </script>
    <% end %>

  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= if signed_into_app?(@conn) do %>
          <div id="profile-links">
            <span id="edit-account-link"> Account </span> |
            <span id="signout-link">
              <%= link "Sign out", to: session_path(@conn, :delete), method: :delete %>
            </span>
          </div>
        <% else %>
          <div id="profile-links">
            <span class="signin-link">Sign In</span> |
            <span class="signup-link">Sign Up</span>
          </div>
        <% end %>

      <div id="search-container">
        <%= form_for @conn, search_path(@conn, :index), [as: :search], fn f -> %>
          <%= text_input f, :query, id: "search-form" %>
          <%= submit "Search", id: "search-submit" %>
        <% end %>
      </div>

      <div id="signin-modal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <%= render "new_session.html", Map.merge(assigns, %{action: Routes.session_path(@conn, :create), oauth_google_url: TreeChat.AuthGoogle.generate_oauth_url(@conn)}) %>
        </div>
      </div>

      <div id="forgot-password-modal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <%= render "forgot_password.html", Map.put(assigns, :action, Routes.password_path(@conn, :create)) %>
        </div>
      </div>

      <div id="signup-modal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <%= render "new_user.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>
        </div>
      </div>

      <div id="edit-account-modal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <%= if signed_into_app?(@conn) do %>
            <%= render "edit_account.html", Map.put(assigns, :action, Routes.user_path(@conn, :edit, String.to_integer(@conn.assigns[:user_id]))) %>
          <% end %>
        </div>
      </div>

      <div id="edit-password-modal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <%= if signed_into_app?(@conn) do %>
            <%= render "edit_password.html", Map.put(assigns, :action, Routes.user_path(@conn, :edit, String.to_integer(@conn.assigns[:user_id]))) %>
          <% end %>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>

      <div id="feedback-link">
        <%= link("Leave Feedback", to: "/c/Feedback") %>
      </div>

      <%= if signed_into_app?(@conn) do %>
        <script>
          window.userToken = "<%= assigns[:user_token] %>";
          window.userName = "<%= assigns[:user_name] %>";
          window.userFirst = "<%= assigns[:user_first] %>";
          window.userLast = "<%= assigns[:user_last] %>";
          window.userId = "<%= assigns[:user_id] %>";
        </script>
      <% end %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/tree_chat_web/templates/layout/edit_account.html.eex
<h3 class="form-header">Account</h3>
<%= form_for Accounts.User.changeset(Accounts.get_user!(@conn.assigns[:user_id]), %{}), user_path(@conn, :update, Accounts.get_user!(@conn.assigns[:user_id])), [as: :user], fn f -> %>
  <div class="form-element">
    <%= text_input f, :first_name, placeholder: "First", required: true, class: "form-input"%>
    <%= error_tag f, :first_name %>
  </div>
  <div class="form-element">
    <%= text_input f, :last_name, placeholder: "Last", required: true, class: "form-input" %>
    <%= error_tag f, :last_name %>
  </div>
  <div class="form-element">
    <%= text_input f, :email, placeholder: "Email", required: true, class: "form-input" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-element">
    <%= text_input f, :username, placeholder: "Username", required: true, class: "form-input" %>
    <%= error_tag f, :username %>
  </div>
  <div class="form-element">
    <%= submit "Update", class: "form-submit" %>
  </div>
<% end %>

<div class="form-element">
  <span id="edit-password-link">Update Password</span>
</div>

lib/tree_chat_web/templates/layout/edit_password.html.eex
<h3 class="form-header">Update Password</h3>
<%= form_for Accounts.User.changeset(Accounts.get_user!(@conn.assigns[:user_id]), %{}), user_path(@conn, :update, Accounts.get_user!(@conn.assigns[:user_id])), [as: :user], fn f -> %>
  <div class="form-element">
    <%= password_input f, :current_password, placeholder: "current password", class: "form-input" %>
    <%= error_tag f, :current_password %>
  </div>
  <div class="form-element">
    <%= password_input f, :encrypted_password, placeholder: "new password", class: "form-input" %>
    <%= error_tag f, :new_password %>
  </div>
  <div class="form-element">
    <%= submit "Update", class: "form-submit" %>
  </div>
<% end %>

lib/tree_chat_web/templates/layout/forgot_password.html.eex
<h3>Forgot Password</h3>

<%= form_for @conn, Routes.password_path(@conn, :create), [as: :forgot_password], fn f -> %>
  <div>
    <%= text_input f, :email, placeholder: "Email", required: true%>
    <%= error_tag f, :email %>
  </div>
  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

lib/tree_chat_web/templates/layout/forgot_username.html.eex
<h3>Sign Up</h3>

<%= form_for @conn, user_path(@conn, :forgot_username), [as: :user], fn f -> %>
  <div>
    <%= text_input f, :email, placeholder: "Email", required: true %>
    <%= error_tag f, :email %>
  </div>
  <div>
    <%= submit "Submit" %>
  </div>
<% end %>

lib/tree_chat_web/templates/layout/new_session.html.eex
<h3 class="form-header">Sign in</h3>
<%= form_for @conn, session_path(@conn, :new), [as: :session], fn f -> %>
  <div class="form-element">
    <%= text_input f, :email, placeholder: "email", required: true, class: "form-input" %><br>
  </div>
  <div class="form-element">
    <%= password_input f, :password, placeholder: "password", required: true, class: "form-input" %><br>
  </div>
  <div class="form-element">
    <%= submit "Sign in", class: "form-submit" %>
  </div>
<% end %>
<div class="form-element">
  <span id="forgot-password-link">Forgot Password?</span>
</div>
<div class="form-element">
  Not a member? <span class="signup-link">Sign Up</span>
</div>

lib/tree_chat_web/templates/layout/new_user.html.eex
<h3 class="form-header">Sign Up</h3>

<%= form_for @conn, user_path(@conn, :create), [as: :user], fn f -> %>
  <div class="form-element">
    <%= text_input f, :email, placeholder: "Email", required: true, class: "form-input" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-element">
    <%= password_input f, :encrypted_password, placeholder: "Choose Password", required: true, class: "form-input" %>
    <%= error_tag f, :encrypted_password %>
  </div>
  <div class="form-element">
    <%= submit "Sign Up", class: "form-submit" %>
  </div>
  <div class="form-element">
    Already a member? <span class="signin-link">Sign In</span>
  </div>
<% end %>